services:
  api:
    build: ./smart_home
    image: app:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=smart_home
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
    networks:
      - smart_home_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=smart_home
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart_home_network

networks:
  smart_home_network:
    driver: bridge
