services:
app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    image: smarthome-app:latest
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy  # Ждем готовности БД
      temperature-api:
        condition: service_started  # Убедимся, что температурный API стартовал
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"  # Проброс порта для основного приложения
    restart: unless-stopped
    networks:
      - smarthome-network
  api:
    build: ./smart_home
    image: app:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=smarthome
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
    networks:
      - smart_home_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=smart_home
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart_home_network

networks:
  smart_home_network:
    driver: bridge
