
openapi: 3.1.0
info:
  title: Smart Home Temperature API
  description: API for managing temperature sensors in a smart home
  version: 1.0.0
paths:
  /sensors:
    get:
      summary: Get All Sensors
      operationId: get_all_sensors_sensors_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                title: Response Get All Sensors Sensors Get
                items:
                  $ref: '#/components/schemas/SensorResponse'
    post:
      summary: Create Sensor
      operationId: create_sensor_sensors_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorCreate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /temperature:
    get:
      summary: Get Temperature
      operationId: get_temperature_temperature_get
      parameters:
        - name: location
          in: query
          required: false
          schema:
            type: string
            default: ''
            title: Location
        - name: sensor_id
          in: query
          required: false
          schema:
            type: string
            default: ''
            title: Sensor Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    SensorCreate:
      title: SensorCreate
      type: object
      required:
        - location
      properties:
        location:
          title: Location
          type: string
        name:
          title: Name
          anyOf:
            - type: string
            - type: 'null'
        type:
          title: Type
          type: string
          default: temperature
        unit:
          title: Unit
          type: string
          default: Celsius
        status:
          title: Status
          type: string
          default: active
    SensorResponse:
      title: SensorResponse
      type: object
      required:
        - id
        - sensor_id
        - name
        - type
        - location
        - value
        - unit
        - status
        - last_updated
        - created_at
      properties:
        id:
          title: Id
          type: integer
        sensor_id:
          title: Sensor Id
          type: string
        name:
          title: Name
          type: string
        type:
          title: Type
          type: string
        location:
          title: Location
          type: string
        value:
          title: Value
          type: number
        unit:
          title: Unit
          type: string
        status:
          title: Status
          type: string
        last_updated:
          title: Last Updated
          type: string
          format: date-time
        created_at:
          title: Created At
          type: string
          format: date-time
    ValidationError:
      title: ValidationError
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
